title: Himalaya Satyal
description: Personal academic website
plugins:
  - jekyll‑remote‑theme

remote_theme: StartBootstrap/startbootstrap‑clean‑blog‑jekyll
author:
  name: Himalaya Satyal

show_downloads: false
